import { useEffect, useState, type CSSProperties, type ReactNode } from 'react'
import type { Ambilight } from '@videoglow/core'
import { useAmbilightState } from '@videoglow/react'

/** Test pattern clips generated by tools/scripts/generate-media-fixtures.mjs (served from apps/examples/public). */
export const MEDIA = {
  landscape: '/media/pattern.webm',
  portrait: '/media/pattern-vertical.webm',
} as const

export const YOUTUBE_VIDEO_ID = 'ASzOzrB-a9E'

/** Dark padded area so the glow has room to spill. */
export function Stage({
  children,
  width = 720,
  style,
}: {
  children: ReactNode
  width?: number | string
  style?: CSSProperties
}) {
  return (
    <div
      style={{
        minHeight: '100vh',
        background: '#0b0b0f',
        display: 'flex',
        justifyContent: 'center',
        padding: '6rem 3rem',
        boxSizing: 'border-box',
        ...style,
      }}
    >
      <div style={{ width: '100%', maxWidth: width }}>{children}</div>
    </div>
  )
}

/** Compact engine statistics for stories. */
export function Readout({ ambilight }: { ambilight: Ambilight | null }) {
  const state = useAmbilightState(ambilight)
  return (
    <pre
      style={{
        color: '#9a9aa8',
        fontSize: 12,
        marginTop: '1.5rem',
        fontFamily: 'ui-monospace, monospace',
      }}
    >
      {`source ${state.sourceKind ?? '-'}/${state.sourceMode ?? '-'}  buffer ${state.bufferWidth}x${state.bufferHeight}  frames ${state.framesRendered}  skipped ${state.framesSkipped}  avg ${state.averageRenderDurationMs.toFixed(3)} ms`}
    </pre>
  )
}

/** Draws moving colored blobs into a canvas at animation frame rate. */
export function useAnimatedCanvas(canvas: HTMLCanvasElement | null, running = true): void {
  useEffect(() => {
    if (!canvas || !running) return
    const ctx = canvas.getContext('2d')
    if (!ctx) return
    let handle = 0
    const draw = (time: number) => {
      const { width, height } = canvas
      ctx.fillStyle = '#05050a'
      ctx.fillRect(0, 0, width, height)
      for (let i = 0; i < 5; i += 1) {
        const t = time / 1000 + i * 1.3
        ctx.fillStyle = `hsl(${(i * 72 + time / 20) % 360} 90% 60%)`
        ctx.beginPath()
        ctx.arc(
          width / 2 + Math.cos(t) * width * 0.3,
          height / 2 + Math.sin(t * 1.7) * height * 0.3,
          Math.min(width, height) * 0.12,
          0,
          Math.PI * 2
        )
        ctx.fill()
      }
      handle = requestAnimationFrame(draw)
    }
    handle = requestAnimationFrame(draw)
    return () => cancelAnimationFrame(handle)
  }, [canvas, running])
}

export function useAmbilightRef(): [Ambilight | null, (instance: Ambilight | null) => void] {
  return useState<Ambilight | null>(null)
}

export const VIDEO_PROPS = {
  controls: true,
  muted: true,
  loop: true,
  autoPlay: true,
  playsInline: true,
} as const
