/** Deterministic test pattern clips generated by tools/scripts/generate-media-fixtures.mjs. */
export const MEDIA = {
  pattern: { webm: '/media/pattern.webm' },
  vertical: { webm: '/media/pattern-vertical.webm' },
} as const

/** The clip used by the original demos. */
export const YOUTUBE_VIDEO_ID = 'I5QDO6BsWnU'
